/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wyyxzrvmgultpiiwaaxc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5eXh6cnZtZ3VsdHBpaXdhYXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODY1MjUsImV4cCI6MjA3Mzk2MjUyNX0.gOQ3uo9rnxZohj7wi-Q6JMMiGBJJNkZJDBQ-B1mHK50"